name: Build
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    name: check
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup | rust
        uses: ./actions/rust-toolchain
      - run: cargo check

  lint:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        cargo-cmd:
          - fmt --all -- --check
          - clippy --all-targets --all-features -- -D warnings
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup | rust
        uses: ./actions/rust-toolchain
      - run: cargo ${{ matrix['cargo-cmd'] }}

  tests:
    name: tests
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        channel: ["nightly", "stable"]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.channel == 'nightly' }}
    steps:
      - uses: actions/checkout@v4
      - name: setup | rust
        uses: ./actions/rust-toolchain
        with:
          channel: ${{ matrix.channel }}
          default: true
          profile: minimal
      - name: cargo test
        run: cargo test --all --locked

  audit:
    name: security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup | rust
        uses: ./actions/rust-toolchain
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - name: audit
        run: cargo deny check advisories bans sources
        continue-on-error: true
